name: securitydept

services:
  securitydept-server:
    # build: .
    image: ghcr.io/aitiotekt/securitydept:latest
    ports:
      - 7021:7021
    environment:
      - SECURITYDEPT_CONFIG=/app/config.toml
    volumes:
      - ./config.toml:/app/config.toml
      - ./custom-claims-check.mts:/app/custom-claims-check.mts
      - ./data:/app/data
      # - ./webui:/app/webui # for custom webui