name: securitydept

services:
  securitydept-server:
    image: ghcr.io/aitiotekt/securitydept:latest
    ports:
      - 8080:8080
    environment:
      - SECURITYDEPT_CONFIG=/app/config.toml
    volumes:
      - config.toml:/app/config.toml
      - ./data:/app/data