[package]
name = "securitydept-server"
version = "0.1.0"
edition = "2024"

[dependencies]
securitydept-core = { path = "../../packages/core" }
axum = { version = "0.8", features = ["macros"] }
tower-http = { version = "0.6", features = ["cors", "fs"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
openidconnect = { workspace = true }

[build-dependencies]
winres = "0.1"
