[package]
name = "securitydept-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true, features = ["fs", "sync", "rt"] }
tracing = { workspace = true }
figment = { version = "0.10", features = ["toml", "env"] }
openidconnect = { workspace = true }
http = "1"
rfc7239 = "0.1"
boa_engine = "0.21"
argon2 = "0.5"
sha2 = "0.10"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.22"
regex = { workspace = true }
serde_with = "3.16.1"
